### ISSUE TITLE
Build is failing with current master.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/lemma-overloading#14]
Travis cron detected a change in Coq that broke lemma-overloading:
https://travis-ci.com/coq-community/lemma-overloading/jobs/154691598#L1796-L1808

```
File "./theories/cancel2.v", line 126, characters 75-79:
Error: Cannot infer the implicit parameter D of prop whose type is
"is_true (def r')" in environment:
x : ptr
A : Type
v : A
r : heap
A' : Type
v' : A'
r' : heap
pf : abs_pts x v' r'
d : def pf
i : x :-> v :+ r = pf
```

I'll try to track down which commit broke it but it would seem that all the candidates are supposed to be internal clean-ups so it looks like a regression.

**Comment by anton-trunov** [comment]
Cool! Thanks for your help.

**Comment by Zimmi48** [comment]
The breakage comes from: https://github.com/coq/coq/pull/8741
This is marked as a clean-up and internal PR so this confirms the regression diagnosis.
Now attempting to minimize the problem to submit a bug report.

**Comment by Zimmi48** [comment]
I opened coq/coq#8848. Since you know this code better than me, you may be able to minimize further...

FTR I first found which commit introduced the bug by running:
```shell
nix-build --argstr coq-version be144dcaa1d1d8ff22e9e39f49fd247e813ac1f8 # fails
nix-build --argstr coq-version 788ff535ed27d5142cd18878f8478bfc161945cd # succeeds
```
thanks to the cron job running every day, there weren't many commits to try.

Then I opened a shell for the failing version (`nix-shell --argstr coq-version be144dcaa1d1d8ff22e9e39f49fd247e813ac1f8`) and I ran `find-bug.py -R theories LemmaOverloading theories/cancel2.v /tmp/bug.v` inside.

**Comment by mattam82** [comment]
That's curious, there are no typeclasses involved in cancel2. It seems to fail because an implicit argument cannot be resolved although we're using program (and the first obligation seems to be exactly what fills that hole).

**Comment by anton-trunov** [comment]
> Since you know this code better than me, you may be able to minimize further...

@Zimmi48 To reproduce the bug from your file, I tried to update my `coq.dev` opam switch to the most recent Coq's `master`, but the build failed:

```shell
#=== ERROR while compiling coq.dev ============================================#
# context     2.0.0~rc2 | macos/x86_64 | base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.06.1 | pinned(git+https://github.com/coq/coq.git#0ac673e5)
# path        ~/.opam/coq.dev/.opam-switch/build/coq.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p coq -j 4
# exit-code   1
# env-file    ~/.opam/log/coq-50785-e235ee.env
# output-file ~/.opam/log/coq-50785-e235ee.out
### output ###
# [...]
# Warning:
# Cannot open /Users/antontrunov/.opam/coq.dev/.opam-switch/build/coq.dev/_build/install/default/theories
# [cannot-open-path,filesystem]
# While loading initial state:
# Warning:
# Cannot open /Users/antontrunov/.opam/coq.dev/.opam-switch/build/coq.dev/_build/install/default/plugins
# [cannot-open-path,filesystem]
# File "./theories/Init/Notations.v", line 128, characters 0-32:
# Error:
# File not found on loadpath : ltac_plugin.cmxs
# Loadpath: /Users/antontrunov/.opam/coq.dev/.opam-switch/build/coq.dev/_build/default
#



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build coq dev
└─
```

Coq's build seems to have switched to Dune, so @ejgallego might know how to fix it.

**Comment by anton-trunov** [comment]
@ejgallego Just updated opam to 2.0.1. Still the error persists:

```shell
$ opam install coq

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><>  🐫
[coq.dev] no changes from git+https://github.com/coq/coq.git

The following actions will be performed:
  ∗ install coq dev*

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] The compilation of coq failed at "/Users/antontrunov/.opam/opam-init/hooks/sandbox.sh build dune build -p coq -j 4".

#=== ERROR while compiling coq.dev ============================================#
# context     2.0.1 | macos/x86_64 | base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.06.1 | pinned(git+https://github.com/coq/coq.git#0ac673e5)
# path        ~/.opam/coq.dev/.opam-switch/build/coq.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p coq -j 4
# exit-code   1
# env-file    ~/.opam/log/coq-78363-d0f245.env
# output-file ~/.opam/log/coq-78363-d0f245.out
### output ###
# [...]
# Warning:
# Cannot open /Users/antontrunov/.opam/coq.dev/.opam-switch/build/coq.dev/_build/install/default/theories
# [cannot-open-path,filesystem]
# While loading initial state:
# Warning:
# Cannot open /Users/antontrunov/.opam/coq.dev/.opam-switch/build/coq.dev/_build/install/default/plugins
# [cannot-open-path,filesystem]
# File "./theories/Init/Notations.v", line 128, characters 0-32:
# Error:
# File not found on loadpath : ltac_plugin.cmxs
# Loadpath: /Users/antontrunov/.opam/coq.dev/.opam-switch/build/coq.dev/_build/default
#



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build coq dev
└─
╶─ No changes have been performed
```

**Comment by mattam82** [comment]
I found the bug, so no need to reproduce for you a priori.

**Comment by Zimmi48** [comment]
@anton-trunov You could also try pinning from the Coq repo. This at least is *supposed* to work.

**Comment by ejgallego** [comment]
That's really strange ummm. @anton-trunov could you open a bug against the main coq repos and send me the whole build log?

What filesystem are you using? What does `ls -l _build/install/bin` says in the build did? Is `coqtop` a symlink?

It seems like you are running in a fs where dune has decided not to use symliks for install. This does indeed break the legacy code for location of coqlib, should be fixed once the windows for dune PR gets in.

**Comment by ejgallego** [comment]
> @anton-trunov You could also try pinning from the Coq repo. This at least is supposed to work.

I dont think that will help here. The build is failing to locate the proper location for coqlib so that issue should be orthogonal to opam I think.

**Comment by anton-trunov** [comment]
> What filesystem are you using?

@ejgallego I'm using `apfs` (according to `mount`: /dev/disk1s1 on / (apfs, local, journaled))

>  What does ls -l _build/install/bin says in the build dir?

```shell
$ ls -l _build/install/bin
ls: cannot access '_build/install/bin': No such file or directory
```

> Is coqtop a symlink?

It seems so:
```
./_build/install/default/bin/coqtop -> ../../../default/topbin/coqtop_bin.exe
```

**Comment by Zimmi48** [comment]
The bug has been fixed in master.

**Comment by anton-trunov** [comment]
@Zimmi48 Thanks a lot!
