### ISSUE TITLE
Following mathcomp conventions for Require Import

### ISSUE THREAD

**Issue by palmskog** [coq-community/lemma-overloading#22]
As far as I can tell, the conventions for `Require Import` in mathcomp are as follows:
```coq
Require Import mathcomp.ssreflect.ssreflect.
From mathcomp
Require Import ssrfun ssrbool eqtype ssrnat seq choice fintype.
From mathcomp
Require Import ssralg finset fingroup morphism perm action countalg.
```
That is, the `ssreflect` plugin is required on a separate line, and the `From mathcomp` is used without further qualifications for the rest.

I'm not sure what the rationale for the separate plugin line is, but it makes sense to me that we don't need qualifications to the `mathcomp` namespace since all modules/files are uniquely named.

 @anton-trunov unless you complain, I'll change to the mathcomp conventions.

**Comment by anton-trunov** [comment]
Sure! No complains :)

**Comment by palmskog** [comment]
OK, while I'm at it, how about switching to `-Q theories LemmaOverloading` instead of `-R theories LemmaOverloading`? I find `-R` a bit annoying since the way the files use each other inside a project differs from how a client uses the files.

For example, where we have:
```coq
Require Import ordtype.
```
we would have to change to
```coq
From LemmaOverloading Require Import ordtype.
```
which is how an external project would use the file anyway.

**Comment by anton-trunov** [comment]
I think you can prepend `From LemmaOverloading` to the local imports even with `-R . fcsl`. AFAIU the description in the manual, in case of a flat file structure there is not difference between `-Q` and `-R`.

**Comment by palmskog** [comment]
OK, right, I'll just add `From LemmaOverloading`.

I agree in principle regarding "equivalence" for a flat file structure, but `-Q` actually forces you to not have "unqualified" `Require Import`s, that's arguably worth something for large projects.

**Comment by anton-trunov** [comment]
> but -Q actually forces you to not have "unqualified" Require Imports, that's arguably worth something for large projects.

I didn't know that, thanks. Feel free then to change to `-Q`. I think this is the case when being more explicit actually helps.
