### ISSUE TITLE
CI for Coq master failing since July 21st

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/lemma-overloading#59]
You might not have noticed yet. I didn't investigate the failure. I suppose a change of either Coq or Math-Comp is responsible.

**Comment by anton-trunov** [comment]
Hey, thanks for letting me know and sorry for the delay. I just tried lemma-overloading on a recent Coq master (commit 873130ae0e8f6079388f4be8259cd893f314e6d5) and Mathcomp master (commit ea1d26eb0f0c3ada5c159dc163cdc811b5d3239d) and it compiles without a single hitch.

**Comment by Zimmi48** [comment]
It seems that there is again a CI issue related to another warning.

**Comment by anton-trunov** [comment]
Oh, I see. Ok, I'm going to turn 'warning-as-errors' off in PR #61

**Comment by anton-trunov** [comment]
Should be fine now.

**Comment by anton-trunov** [comment]
I guess this can be closed now, feel free to reopen.
